[update] Add Eslint to pre-commit

diff --git a/git-hooks/pre-commit b/git-hooks/pre-commit
--- a/git-hooks/pre-commit
+++ b/git-hooks/pre-commit
@@ -33,8 +33,33 @@ done
 
 echo "\nPHPCS validation completed!\n"
 
+echo "\nValidating Javascript:\n"
+
+# Check for eslint
+which ./src/eslint &> /dev/null
+if [[ "$?" == 1 ]]; then
+  echo "\t\033[41mPlease install ESlint\033[0m"
+  exit 1
+fi
+
+STAGED_JS_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep ".(js|vue)\{0,1\}$")
+
+for FILE in $STAGED_JS_FILES
+do
+  eslint "$FILE"
+
+  if [[ "$?" == 0 ]]; then
+    echo "\t\033[32mESLint Passed: $FILE\033[0m"
+  else
+    echo "\t\033[41mESLint Failed: $FILE\033[0m"
+    PASS=false
+  fi
+done
+
+echo "\nJavascript validation completed!\n"
+
 if ! $PASS; then
-  echo "\033[41mCOMMIT FAILED:\033[0m Your commit contains files that should pass PHPCS but do not. Please fix the PHPCS errors and try again.\n"
+  echo "\033[41mCOMMIT FAILED:\033[0m Your commit contains files that should pass PHPCS and Eslint but do not. Please fix the PHPCS and Eslint errors and try again.\n"
   exit 1
 else
   echo "\033[42mCOMMIT SUCCEEDED\033[0m\n"
